language: objective-c
osx_image: xcode8
rvm:
  - 2.2.2

env:
  global:
    - WORKSPACE="Titan.xcworkspace"
    - OSX_APP_SCHEME="Titan"
    - OSX_SDK=macosx10.12
  matrix:
    - DESTINATION="arch=x86_64"                      SCHEME="$OSX_APP_SCHEME"           SDK="$OSX_SDK"     RUN_TESTS="NO"    BUILD_EXAMPLE="YES"

before_install:
  - gem install cocoapods

script:
  - pod install
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
